# Generated by Django 6.0.3 on 2026-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_grocery_ingredient_grocery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='for_recipe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('missing', 'Missing')], default='available', max_length=20),
        ),
    ]
