# Generated by Django 6.0.4 on 2026-05-08 15:50

from django.db import migrations, models


def seed_ingredients_from_recipe_groceries(apps, schema_editor):
    Ingredient = apps.get_model('pages', 'Ingredient')
    Grocery = apps.get_model('pages', 'Grocery')
    table = 'pages_recipe_ingredients'

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'SELECT DISTINCT grocery_id FROM {table}')
        grocery_ids = [row[0] for row in cursor.fetchall()]

    name_to_ingredient_id = {}
    for grocery in Grocery.objects.filter(id__in=grocery_ids).order_by('id'):
        name = (grocery.name or grocery.custom_name or f'Ingredient {grocery.id}').strip()
        existing_id = name_to_ingredient_id.get(name)

        if existing_id is None:
            ingredient, _ = Ingredient.objects.get_or_create(
                name=name,
                defaults={'id': grocery.id},
            )
            existing_id = ingredient.id
            name_to_ingredient_id[name] = existing_id

        if existing_id != grocery.id:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    f'UPDATE {table} SET grocery_id = %s WHERE grocery_id = %s',
                    [existing_id, grocery.id],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_recipe_image_url_favouriterecipe_delete_savedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(seed_ingredients_from_recipe_groceries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='pages.ingredient'),
        ),
    ]
