# Generated by Django 6.0.4 on 2026-05-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_grocery_quantity'),
        ('pages', '0011_ingredient_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
