# Generated by Django 6.0.4 on 2026-05-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_grocery_quantity'),
        ('pages', '0012_grocery_quantity'),
    ]

    operations = [
    ]
