# Generated by Django 6.0.4 on 2026-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_merge_0010_grocery_quantity_0012_grocery_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
