# Generated by Django 6.0.3 on 2026-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_merge_20260511_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
