# Generated by Django 6.0.3 on 2026-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
