# Generated by Django 6.0.3 on 2026-06-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_recipe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_url',
            new_name='image',
        ),
    ]
