# Generated by Django 6.0.4 on 2026-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
