# Generated by Django 6.0.4 on 2026-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert')], default='lunch', max_length=50)),
                ('appliance', models.CharField(choices=[('none', 'No Appliance Needed'), ('microwave', 'Microwave'), ('oven', 'Oven'), ('stove', 'Stove'), ('airfryer', 'Air Fryer'), ('blender', 'Blender')], default='stove', max_length=50)),
                ('budget', models.CharField(choices=[('low', 'Budget Friendly (Below RM5)'), ('medium', 'Moderate (RM5 - RM15)'), ('high', 'Splurge (Above RM15)')], default='low', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_minutes', models.IntegerField(help_text='Cooking time in minutes')),
                ('is_halal', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
