# Generated by Django 6.0.4 on 2026-04-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFilters',
            fields=[
                ('recipe_filters_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_filters_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('recipe_id', models.IntegerField(blank=True, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('saved_recipe_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('saved_recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_recipe_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesite.user')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredients_id', models.IntegerField()),
                ('ingredients_name', models.CharField(max_length=100)),
                ('recipe_filters_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesite.recipefilters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('ingredients_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentary', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesite.user')),
            ],
        ),
    ]
