# Generated by Django 6.0.4 on 2026-04-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='groceries',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='recipe_filters_id',
            new_name='recipe_filters',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedrecipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='ingredients_id',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='ingredients_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_recipe_id',
        ),
    ]
