"""
Django settings for campuscook project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
 
BASE_DIR = Path(__file__).resolve().parent.parent
 
SECRET_KEY = 'django-insecure-l83i3=2!oqdm8-e%wd-astdk$x#gdnw0lva98h3hds35^38ms*'
 
DEBUG = True
 
ALLOWED_HOSTS = []
 
# Application definition
 
AUTH_USER_MODEL = 'pages.AppUser'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'campuscook.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'campuscook.wsgi.application'
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
 
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
 
STATIC_URL = 'static/'
 
# ── Email configuration ───────────────────────────────────────────────────────
# For development: print emails to the console instead of sending them.
# Switch to an SMTP backend in production (see commented block below).
 
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Campus Cook <noreply@campuscook.com>'
 
# ── Production SMTP (e.g. Gmail) ─────────────────────────────────────────────
# Uncomment and fill in these settings when deploying:
#
# EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST       = 'smtp.gmail.com'
# EMAIL_PORT       = 587
# EMAIL_USE_TLS    = True
# EMAIL_HOST_USER  = 'your-gmail@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'   # use a Gmail App Password, not your real password
# DEFAULT_FROM_EMAIL = 'Campus Cook <your-gmail@gmail.com>'
#
# For other providers replace EMAIL_HOST / PORT accordingly.
# Never commit real credentials — use environment variables instead:
#   EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER')
#   EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
 