# Generated by Django 6.0.3 on 2026-04-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_appuser_options_alter_appuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='filters',
            field=models.ManyToManyField(blank=True, to='pages.recipefilter'),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together={('user', 'recipe')},
        ),
    ]
