# Generated by Django 6.0.3 on 2026-05-02 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_appuser_password_alter_recipe_filters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='grocery',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='pages.grocery'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='pages.recipe'),
        ),
        migrations.DeleteModel(
            name='CustomIngredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
