# Generated by Django 6.0.4 on 2026-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_grocery_for_recipe_grocery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
