# Generated by Django 6.0.4 on 2026-04-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_grocery_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='quantity',
        ),
    ]
