# Generated by Django 6.0.4 on 2026-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_grocery_custom_name_alter_grocery_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='filters',
            field=models.ManyToManyField(blank=True, null=True, to='pages.recipefilter'),
        ),
    ]
