# Generated by Django 6.0.3 on 2026-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_grocery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='budget',
            field=models.CharField(choices=[('low', 'Below RM5'), ('medium', 'RM5 – RM15'), ('high', 'Above RM15')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_halal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('missing', 'Missing'), ('purchased', 'Purchased')], default='available', max_length=20),
        ),
    ]
