# Generated by Django 6.0.3 on 2026-05-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_comment_options_comment_created_at_and_more'),
        ('pages', '0015_recipe_budget_recipe_is_halal_alter_grocery_status'),
    ]

    operations = [
    ]
