# Generated by Django 6.0.3 on 2026-07-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_wanttotry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='filters',
        ),
        migrations.DeleteModel(
            name='RecipeFilter',
        ),
    ]
